---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kwok-manager
  namespace: kube-system
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kwok-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kwok-manager
  namespace: kube-system
...
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: kwok
  name: kwok
  namespace: kube-system
spec:
  containers:
  - image: registry.k8s.io/kwok/kwok:v0.7.0
    imagePullPolicy: IfNotPresent
    name: kwok
    args:
    - --manage-nodes-with-label-selector
    - kwok.x-k8s.io/node=fake
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  serviceAccount: kwok-manager
  serviceAccountName: kwok-manager
  terminationGracePeriodSeconds: 30
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
  tolerations:
  - operator: "Exists"
    effect: "NoSchedule"
...
