---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kwok-controller
  name: kwok-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kwok-controller
  name: kwok-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  - pods/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kwok.x-k8s.io
  resources:
  - attaches
  - clusterattaches
  - clusterexecs
  - clusterlogs
  - clusterportforwards
  - clusterresourceusages
  - execs
  - logs
  - metrics
  - portforwards
  - resourceusages
  - stages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kwok.x-k8s.io
  resources:
  - attaches/status
  - clusterattaches/status
  - clusterexecs/status
  - clusterlogs/status
  - clusterportforwards/status
  - clusterresourceusages/status
  - execs/status
  - logs/status
  - metrics/status
  - portforwards/status
  - resourceusages/status
  - stages/status
  verbs:
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kwok-controller
  name: kwok-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kwok-controller
subjects:
- kind: ServiceAccount
  name: kwok-controller
  namespace: kube-system
---
apiVersion: v1
data:
  kwok.yaml: |
    apiVersion: config.kwok.x-k8s.io/v1alpha1
    kind: KwokConfiguration
    options:
      enableProfilingHandler: false
      enableContentionProfiling: false
      enablePodsOnNodeSyncListPager: false
      enablePodsOnNodeSyncStreamWatch: true
      nodeLeaseParallelism: 4
      podPlayStageParallelism: 4
      nodePlayStageParallelism: 4
      nodePort: 10247
      cidr: 10.0.0.1/24
      manageAllNodes: false
      manageNodesWithAnnotationSelector: 'kwok.x-k8s.io/node=fake'
      manageNodesWithLabelSelector: ''
      manageSingleNode: ''
      nodeLeaseDurationSeconds: 40
      enableCRDs:
      - Stage
      - Metric
      - Attach
      - ClusterAttach
      - Exec
      - ClusterExec
      - Logs
      - ClusterLogs
      - PortForward
      - ClusterPortForward
      - ResourceUsage
      - ClusterResourceUsage
kind: ConfigMap
metadata:
  labels:
    app: kwok-controller
  name: kwok
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kwok-controller
  name: kwok-controller
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 10247
    protocol: TCP
    targetPort: 10247
  selector:
    app: kwok-controller
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kwok-controller
  name: kwok-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwok-controller
  template:
    metadata:
      labels:
        app: kwok-controller
    spec:
      containers:
      - args:
        - --config=/root/.kwok/kwok.yaml
        - --node-ip=$(POD_IP)
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: registry.k8s.io/kwok/kwok:v0.7.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: 10247
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        name: kwok-controller
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 10247
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 20
          timeoutSeconds: 2
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10247
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /root/.kwok/kwok.yaml
          name: kwok-config
          readOnly: true
          subPath: kwok.yaml
      restartPolicy: Always
      serviceAccountName: kwok-controller
      volumes:
      - configMap:
          name: kwok
        name: kwok-config
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  labels:
    app: kwok-controller
  name: kwok-controller
  namespace: kube-system
spec:
  matchingPrecedence: 1000
  priorityLevelConfiguration:
    name: exempt
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: kwok-controller
        namespace: kube-system
